<template>
  <div class="content-box">
    <h2 class="demo-title">nui 图标</h2>
    <p class="demo-introduction">语义化的矢量图形。</p>

    <div class="demo-tip">
      <p>该项目使用 Ant Design 官方图标库</p>
    </div>

    <div class="nui-nui" id="nui-simple">
      <!-- 常用图标 -->
      <div id="nui-ofen-list">
        <h3 class="demo-table-title">常用图标</h3>
        <ul class="nui-list">
          <li
            :class="{ rigth_block: index % 5 === 4 }"
            :key="item"
            v-for="(item, index) in ofen_icon_list"
          >
            <div>
              <i :class="item" class="nuii"></i>
              <p class="nui-name">{{ item }}</p>
            </div>
          </li>
        </ul>
      </div>

      <!-- 图标集合 -->
      <div id="nui-list">
        <h3 class="demo-table-title">图标集合</h3>
        <ul class="nui-list">
          <li
            :class="{ rigth_block: index % 5 === 4 }"
            :key="item"
            v-for="(item, index) in icon_list"
          >
            <div>
              <i :class="item" class="nuii"></i>
              <p class="nui-name">{{ item }}</p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: "nuiIcon",
  data() {
    return {
      //基础用法DEMO
      simple: {
        code: {
          html: `
          <i class="nuii nui-calendar-check"></i>
          <i class="nuii nui-share"></i>
          <i class="nuii nui-search"></i>
          <i class="nuii nui-star-fill"></i>
          <i class="nuii nui-edit-fill"></i>
          <i class="nuii nui-alipay"></i>
          <i class="nuii nui-taobao"></i>
          <i class="nuii nui-QQ"></i>
          <i class="nuii nui-weibo"></i>
          <i class="nuii nui-wechat-fill"></i>
          <i class="nuii nui-github-fill"></i>

          `
        }
      },
      ofen_icon_list: [
        "nui-reload",
        "nui-message",
        "nui-poweroff",
        "nui-setting",
        "nui-eye",
        "nui-export",
        "nui-location",
        "nui-edit-square",
        "nui-play-square",
        "nui-adduser",
        "nui-addteam",
        "nui-user",
        "nui-steam",
        "nui-file-image",
        "nui-file-unknown",
        "nui-file",
        "nui-like",
        "nui-unlike",
        "nui-cloud-upload",
        "nui-cloud-download",
        "nui-mail",
        "nui-heart",
        "nui-star",
        "nui-right",
        "nui-left",
        "nui-up",
        "nui-down",
        "nui-question",
        "nui-close_1",
        "nui-close",
        "nui-line",
        "nui-drag",
        "nui-folder-fill",
        "nui-cloud-fill",
        "nui-star-fill",
        "nui-eye-fill",
        "nui-like-fill",
        "nui-unlike-fill",
        "nui-zoomout",
        "nui-zoomin",
        "nui-plus"
      ],
      icon_list: [
        "nui-xiaochengxu",
        "nui-muyingwanju",
        "nui-steam-fill",
        "nui-close_1",
        "nui-check-circle",
        "nui-CI",
        "nui-Dollar",
        "nui-compass",
        "nui-close-circle",
        "nui-frown",
        "nui-info-circle",
        "nui-left-circle",
        "nui-down-circle",
        "nui-EURO",
        "nui-copyright",
        "nui-minus-circle",
        "nui-meh",
        "nui-plus-circle",
        "nui-play-circle",
        "nui-question-circle",
        "nui-Pound",
        "nui-right-circle",
        "nui-smile",
        "nui-trademark",
        "nui-time-circle",
        "nui-timeout",
        "nui-earth",
        "nui-YUAN",
        "nui-up-circle",
        "nui-warning-circle",
        "nui-sync",
        "nui-transaction",
        "nui-undo",
        "nui-redo",
        "nui-reload",
        "nui-reloadtime",
        "nui-message",
        "nui-dashboard",
        "nui-issuesclose",
        "nui-poweroff",
        "nui-logout",
        "nui-piechart",
        "nui-setting",
        "nui-eye",
        "nui-location",
        "nui-edit-square",
        "nui-export",
        "nui-save",
        "nui-Import",
        "nui-appstore",
        "nui-close-square",
        "nui-down-square",
        "nui-layout",
        "nui-left-square",
        "nui-play-square",
        "nui-control",
        "nui-codelibrary",
        "nui-detail",
        "nui-minus-square",
        "nui-plus-square",
        "nui-right-square",
        "nui-project",
        "nui-wallet",
        "nui-up-square",
        "nui-calculator",
        "nui-interation",
        "nui-check-square",
        "nui-border",
        "nui-border-outer",
        "nui-border-top",
        "nui-border-bottom",
        "nui-border-left",
        "nui-border-right",
        "nui-border-inner",
        "nui-border-verticle",
        "nui-border-horizontal",
        "nui-radius-bottomleft",
        "nui-radius-bottomright",
        "nui-radius-upleft",
        "nui-radius-upright",
        "nui-radius-setting",
        "nui-adduser",
        "nui-deleteteam",
        "nui-deleteuser",
        "nui-addteam",
        "nui-user",
        "nui-team",
        "nui-areachart",
        "nui-linechart",
        "nui-barchart",
        "nui-pointmap",
        "nui-container",
        "nui-database",
        "nui-sever",
        "nui-mobile",
        "nui-tablet",
        "nui-redenvelope",
        "nui-book",
        "nui-filedone",
        "nui-reconciliation",
        "nui-file-exception",
        "nui-filesync",
        "nui-filesearch",
        "nui-solution",
        "nui-fileprotect",
        "nui-file-add",
        "nui-file-excel",
        "nui-file-exclamation",
        "nui-file-pdf",
        "nui-file-image",
        "nui-file-markdown",
        "nui-file-unknown",
        "nui-file-ppt",
        "nui-file-word",
        "nui-file",
        "nui-file-zip",
        "nui-file-text",
        "nui-file-copy",
        "nui-snippets",
        "nui-audit",
        "nui-diff",
        "nui-Batchfolding",
        "nui-securityscan",
        "nui-propertysafety",
        "nui-safetycertificate",
        "nui-insurance",
        "nui-alert",
        "nui-delete",
        "nui-hourglass",
        "nui-bulb",
        "nui-experiment",
        "nui-bell",
        "nui-trophy",
        "nui-rest",
        "nui-USB",
        "nui-skin",
        "nui-home",
        "nui-bank",
        "nui-filter",
        "nui-funnelplot",
        "nui-like",
        "nui-unlike",
        "nui-unlock",
        "nui-lock",
        "nui-customerservice",
        "nui-flag",
        "nui-moneycollect",
        "nui-medicinebox",
        "nui-shop",
        "nui-rocket",
        "nui-shopping",
        "nui-folder",
        "nui-folder-open",
        "nui-folder-add",
        "nui-deploymentunit",
        "nui-accountbook",
        "nui-contacts",
        "nui-carryout",
        "nui-calendar-check",
        "nui-calendar",
        "nui-scan",
        "nui-select",
        "nui-boxplot",
        "nui-build",
        "nui-sliders",
        "nui-laptop",
        "nui-barcode",
        "nui-camera",
        "nui-cluster",
        "nui-gateway",
        "nui-car",
        "nui-printer",
        "nui-read",
        "nui-cloud-server",
        "nui-cloud-upload",
        "nui-cloud",
        "nui-cloud-download",
        "nui-cloud-sync",
        "nui-video",
        "nui-notification",
        "nui-sound",
        "nui-radarchart",
        "nui-qrcode",
        "nui-fund",
        "nui-image",
        "nui-mail",
        "nui-table",
        "nui-idcard",
        "nui-creditcard",
        "nui-heart",
        "nui-block",
        "nui-error",
        "nui-star",
        "nui-gold",
        "nui-heatmap",
        "nui-wifi",
        "nui-attachment",
        "nui-edit",
        "nui-key",
        "nui-api",
        "nui-disconnect",
        "nui-highlight",
        "nui-monitor",
        "nui-link",
        "nui-man",
        "nui-percentage",
        "nui-pushpin",
        "nui-phone",
        "nui-shake",
        "nui-tag",
        "nui-wrench",
        "nui-tags",
        "nui-scissor",
        "nui-mr",
        "nui-share",
        "nui-branches",
        "nui-fork",
        "nui-shrink",
        "nui-arrawsalt",
        "nui-verticalright",
        "nui-verticalleft",
        "nui-right",
        "nui-left",
        "nui-up",
        "nui-down",
        "nui-fullscreen",
        "nui-fullscreen-exit",
        "nui-doubleleft",
        "nui-doubleright",
        "nui-arrowright",
        "nui-arrowup",
        "nui-arrowleft",
        "nui-arrowdown",
        "nui-upload",
        "nui-colum-height",
        "nui-vertical-align-botto",
        "nui-vertical-align-middl",
        "nui-totop",
        "nui-vertical-align-top",
        "nui-download",
        "nui-sort-descending",
        "nui-sort-ascending",
        "nui-fall",
        "nui-swap",
        "nui-stock",
        "nui-rise",
        "nui-indent",
        "nui-outdent",
        "nui-menu",
        "nui-unorderedlist",
        "nui-orderedlist",
        "nui-align-right",
        "nui-align-center",
        "nui-align-left",
        "nui-pic-center",
        "nui-pic-right",
        "nui-pic-left",
        "nui-bold",
        "nui-font-colors",
        "nui-exclaimination",
        "nui-font-size",
        "nui-infomation",
        "nui-line-height",
        "nui-strikethrough",
        "nui-underline",
        "nui-number",
        "nui-italic",
        "nui-code",
        "nui-column-width",
        "nui-check",
        "nui-ellipsis",
        "nui-dash",
        "nui-close",
        "nui-enter",
        "nui-line",
        "nui-minus",
        "nui-question",
        "nui-rollback",
        "nui-small-dash",
        "nui-pause",
        "nui-bg-colors",
        "nui-crown",
        "nui-drag",
        "nui-desktop",
        "nui-gift",
        "nui-stop",
        "nui-fire",
        "nui-thunderbolt",
        "nui-check-circle-fill",
        "nui-left-circle-fill",
        "nui-down-circle-fill",
        "nui-minus-circle-fill",
        "nui-close-circle-fill",
        "nui-info-circle-fill",
        "nui-up-circle-fill",
        "nui-right-circle-fill",
        "nui-plus-circle-fill",
        "nui-question-circle-fill",
        "nui-EURO-circle-fill",
        "nui-frown-fill",
        "nui-copyright-circle-fil",
        "nui-CI-circle-fill",
        "nui-compass-fill",
        "nui-Dollar-circle-fill",
        "nui-poweroff-circle-fill",
        "nui-meh-fill",
        "nui-play-circle-fill",
        "nui-Pound-circle-fill",
        "nui-smile-fill",
        "nui-stop-fill",
        "nui-warning-circle-fill",
        "nui-time-circle-fill",
        "nui-trademark-circle-fil",
        "nui-YUAN-circle-fill",
        "nui-heart-fill",
        "nui-piechart-circle-fil",
        "nui-dashboard-fill",
        "nui-message-fill",
        "nui-check-square-fill",
        "nui-down-square-fill",
        "nui-minus-square-fill",
        "nui-close-square-fill",
        "nui-codelibrary-fill",
        "nui-left-square-fill",
        "nui-play-square-fill",
        "nui-up-square-fill",
        "nui-right-square-fill",
        "nui-plus-square-fill",
        "nui-accountbook-fill",
        "nui-carryout-fill",
        "nui-calendar-fill",
        "nui-calculator-fill",
        "nui-interation-fill",
        "nui-project-fill",
        "nui-detail-fill",
        "nui-save-fill",
        "nui-wallet-fill",
        "nui-control-fill",
        "nui-layout-fill",
        "nui-appstore-fill",
        "nui-mobile-fill",
        "nui-tablet-fill",
        "nui-book-fill",
        "nui-redenvelope-fill",
        "nui-safetycertificate-f",
        "nui-propertysafety-fill",
        "nui-insurance-fill",
        "nui-securityscan-fill",
        "nui-file-exclamation-fil",
        "nui-file-add-fill",
        "nui-file-fill",
        "nui-file-excel-fill",
        "nui-file-markdown-fill",
        "nui-file-text-fill",
        "nui-file-ppt-fill",
        "nui-file-unknown-fill",
        "nui-file-word-fill",
        "nui-file-zip-fill",
        "nui-file-pdf-fill",
        "nui-file-image-fill",
        "nui-diff-fill",
        "nui-file-copy-fill",
        "nui-snippets-fill",
        "nui-batchfolding-fill",
        "nui-reconciliation-fill",
        "nui-folder-add-fill",
        "nui-folder-fill",
        "nui-folder-open-fill",
        "nui-database-fill",
        "nui-container-fill",
        "nui-sever-fill",
        "nui-calendar-check-fill",
        "nui-image-fill",
        "nui-idcard-fill",
        "nui-creditcard-fill",
        "nui-fund-fill",
        "nui-read-fill",
        "nui-contacts-fill",
        "nui-delete-fill",
        "nui-notification-fill",
        "nui-flag-fill",
        "nui-moneycollect-fill",
        "nui-medicinebox-fill",
        "nui-rest-fill",
        "nui-shopping-fill",
        "nui-skin-fill",
        "nui-video-fill",
        "nui-sound-fill",
        "nui-bulb-fill",
        "nui-bell-fill",
        "nui-filter-fill",
        "nui-fire-fill",
        "nui-funnelplot-fill",
        "nui-gift-fill",
        "nui-hourglass-fill",
        "nui-home-fill",
        "nui-trophy-fill",
        "nui-location-fill",
        "nui-cloud-fill",
        "nui-customerservice-fill",
        "nui-experiment-fill",
        "nui-eye-fill",
        "nui-like-fill",
        "nui-lock-fill",
        "nui-unlike-fill",
        "nui-star-fill",
        "nui-unlock-fill",
        "nui-alert-fill",
        "nui-api-fill",
        "nui-highlight-fill",
        "nui-phone-fill",
        "nui-edit-fill",
        "nui-pushpin-fill",
        "nui-rocket-fill",
        "nui-thunderbolt-fill",
        "nui-tag-fill",
        "nui-wrench-fill",
        "nui-tags-fill",
        "nui-bank-fill",
        "nui-camera-fill",
        "nui-error-fill",
        "nui-crown-fill",
        "nui-mail-fill",
        "nui-car-fill",
        "nui-printer-fill",
        "nui-shop-fill",
        "nui-setting-fill",
        "nui-USB-fill",
        "nui-golden-fill",
        "nui-build-fill",
        "nui-boxplot-fill",
        "nui-sliders-fill",
        "nui-alibaba",
        "nui-alibabacloud",
        "nui-antdesign",
        "nui-ant-cloud",
        "nui-behance",
        "nui-googleplus",
        "nui-medium",
        "nui-google",
        "nui-IE",
        "nui-amazon",
        "nui-slack",
        "nui-alipay",
        "nui-taobao",
        "nui-zhihu",
        "nui-HTML",
        "nui-linkedin",
        "nui-yahoo",
        "nui-facebook",
        "nui-skype",
        "nui-CodeSandbox",
        "nui-chrome",
        "nui-codepen",
        "nui-aliwangwang",
        "nui-apple",
        "nui-android",
        "nui-sketch",
        "nui-Gitlab",
        "nui-dribbble",
        "nui-instagram",
        "nui-reddit",
        "nui-windows",
        "nui-yuque",
        "nui-Youtube",
        "nui-Gitlab-fill",
        "nui-dropbox",
        "nui-dingtalk",
        "nui-android-fill",
        "nui-apple-fill",
        "nui-HTML-fill",
        "nui-windows-fill",
        "nui-QQ",
        "nui-twitter",
        "nui-skype-fill",
        "nui-weibo",
        "nui-yuque-fill",
        "nui-Youtube-fill",
        "nui-yahoo-fill",
        "nui-wechat-fill",
        "nui-chrome-fill",
        "nui-alipay-circle-fill",
        "nui-aliwangwang-fill",
        "nui-behance-circle-fill",
        "nui-amazon-circle-fill",
        "nui-codepen-circle-fill",
        "nui-CodeSandbox-circle-f",
        "nui-dropbox-circle-fill",
        "nui-github-fill",
        "nui-dribbble-circle-fill",
        "nui-googleplus-circle-f",
        "nui-medium-circle-fill",
        "nui-QQ-circle-fill",
        "nui-IE-circle-fill",
        "nui-google-circle-fill",
        "nui-dingtalk-circle-fill",
        "nui-sketch-circle-fill",
        "nui-slack-circle-fill",
        "nui-twitter-circle-fill",
        "nui-taobao-circle-fill",
        "nui-weibo-circle-fill",
        "nui-zhihu-circle-fill",
        "nui-reddit-circle-fill",
        "nui-alipay-square-fill",
        "nui-dingtalk-square-fill",
        "nui-CodeSandbox-square-f",
        "nui-behance-square-fill",
        "nui-amazon-square-fill",
        "nui-codepen-square-fill",
        "nui-dribbble-square-fill",
        "nui-dropbox-square-fill",
        "nui-facebook-fill",
        "nui-googleplus-square-f",
        "nui-google-square-fill",
        "nui-instagram-fill",
        "nui-IE-square-fill",
        "nui-medium-square-fill",
        "nui-linkedin-fill",
        "nui-QQ-square-fill",
        "nui-reddit-square-fill",
        "nui-twitter-square-fill",
        "nui-sketch-square-fill",
        "nui-slack-square-fill",
        "nui-taobao-square-fill",
        "nui-weibo-square-fill",
        "nui-zhihu-square-fill",
        "nui-zoomout",
        "nui-apartment",
        "nui-audio",
        "nui-audio-fill",
        "nui-robot",
        "nui-zoomin",
        "nui-robot-fill",
        "nui-bug-fill",
        "nui-bug",
        "nui-audiostatic",
        "nui-comment",
        "nui-signal-fill",
        "nui-verified",
        "nui-shortcut-fill",
        "nui-videocameraadd",
        "nui-switchuser",
        "nui-whatsapp",
        "nui-appstoreadd",
        "nui-caret-down",
        "nui-backward",
        "nui-caret-up",
        "nui-caret-right",
        "nui-caret-left",
        "nui-fast-backward",
        "nui-forward",
        "nui-fast-forward",
        "nui-search",
        "nui-retweet",
        "nui-login",
        "nui-step-backward",
        "nui-step-forward",
        "nui-swap-right",
        "nui-swap-left",
        "nui-woman",
        "nui-steam",
        "nui-plus",
        "nui-eyeclose-fill",
        "nui-eye-close",
        "nui-clear",
        "nui-collapse",
        "nui-expand",
        "nui-deletecolumn",
        "nui-merge-cells",
        "nui-subnode",
        "nui-rotate-left",
        "nui-rotate-right",
        "nui-insertrowbelow",
        "nui-insertrowabove",
        "nui-table1",
        "nui-solit-cells",
        "nui-formatpainter",
        "nui-insertrowright",
        "nui-formatpainter-fill",
        "nui-insertrowleft",
        "nui-translate",
        "nui-deleterow",
        "nui-sisternode",
        "nui-Field-number",
        "nui-Field-String",
        "nui-Function",
        "nui-Field-time",
        "nui-GIF",
        "nui-Partition",
        "nui-index",
        "nui-Storedprocedure",
        "nui-Field-Binary",
        "nui-Console-SQL",
        "nui-icon-test",
        "nui-aim",
        "nui-compress",
        "nui-expend",
        "nui-folder-view",
        "nui-file-GIF",
        "nui-group",
        "nui-send",
        "nui-Report",
        "nui-View",
        "nui-shortcut",
        "nui-ungroup"
      ]
    };
  }
};
</script>
<style lang="scss" scoped>
.nui-nui {
  i {
    font-size: 28px;
  }
  .nui-list {
    width: 100%;
    overflow: hidden;
    list-style: none;
    padding: 0 !important;
    // border: 1px solid #eaeefb;
    border-radius: 4px;
    // .rigth_block {
    //   border-right: 0 !important;
    // }
    li {
      float: left;
      border: 1px solid #eaeefb;
      width: 19%;
      text-align: center;
      height: 166px;
      color: #666;
      font-size: 13px;
      // border-right: 1px solid #eee;
      // border-bottom: 1px solid #eee;
      display: flex;
      justify-content: center;
      align-items: center;
      transition: all 0.15s ease-in-out;
      &:hover {
        background: #409eff;
        div {
          color: #fff;
        }
        i {
          color: #fff;
          font-size: 40px;
        }
      }
      div {
        font-family: Helvetica Neue, Helvetica, PingFang SC, Hiragino Sans GB,
          Microsoft YaHei, SimSun, sans-serif;
        color: #99a9bf;
        transition: all 0.15s ease-in-out;
        i {
          font-size: 32px;
          color: #606266;
          transition: all 0.15s ease-in-out;
        }
        .nui-name {
          padding: 20px 0;
          height: 1em;
        }
      }
    }
  }
}
</style>
